import { Router } from 'express';
import healthCheck from './health-check.js';
import stripeRouter from './stripe.js';
import featuresRouter from './features.js';
import slackRouter from './slack.js';
import authRouter from './auth.js';
import clientesRouter from './clientes.js';
import tareasRouter from './tareas.js';
import seguimientosRouter from './seguimientos.js';
import ventasRouter from './ventas.js';
import productosRouter from './productos.js';
import emailsRouter from './emails.js';
import plantillasRouter from './plantillas.js';
import notificacionesRouter from './notificaciones.js';
import actividadRouter from './actividad.js';
import usuariosRouter from './usuarios.js';
import importRouter from './import.js';
import reportsRouter from './reports.js';
import automatizacionesRouter from './automatizaciones.js';
import searchRouter from './search.js';
import integracionesRouter from './integraciones.js';
import categoriasRouter from './categorias.js';

const router = Router();

export default () => {
  router.get('/health', healthCheck);
  router.use('/api/auth', authRouter);
  router.use('/api/clientes', clientesRouter);
  router.use('/api/tareas', tareasRouter);
  router.use('/api/seguimientos', seguimientosRouter);
  router.use('/api/ventas', ventasRouter);
  router.use('/api/productos', productosRouter);
  router.use('/api/emails', emailsRouter);
  router.use('/api/plantillas', plantillasRouter);
  router.use('/api/notificaciones', notificacionesRouter);
  router.use('/api/actividad', actividadRouter);
  router.use('/api/usuarios', usuariosRouter);
  router.use('/api/reports', reportsRouter);
  router.use('/api/automatizaciones', automatizacionesRouter);
  router.use('/api/search', searchRouter);
  router.use('/api/integraciones', integracionesRouter);
  router.use('/api/categorias', categoriasRouter);
  router.use('/stripe', stripeRouter);
  router.use('/features', featuresRouter);
  router.use('/slack', slackRouter);
  router.use('/import', importRouter);
  return router;
};
